name: Tests unitaires Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest requests pytest-django pytest-cov

      - name: Lancer les tests Django internes (models/views)
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
        run: |
          python manage.py test base

      - name: Lancer les tests Pytest avec coverage (sur le code Django)
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
        run: |
          pytest --ds=backend.settings --cov=base --cov-report=term --cov-report=html

      - name: Lancer les tests externes API (test_main.py)
        run: |
          pytest .github/workflows/test_main.py

