name: Tests unitaires Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-django pytest-cov requests

      - name: Lancer les tests Django avec couverture
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
        run: |
          cd backend
          pytest base --ds=backend.settings --cov=base --cov-report=term --cov-report=html

      - name: Upload du rapport de couverture
        uses: actions/upload-artifact@v3
        with:
          name: rapport-couverture-html
          path: backend/htmlcov

      - name: Lancer les tests externes (API en ligne)
        run: |
          pytest .github/workflows/test_main.py
